---
title: 'NOAA Plot Replication and Variation'
author: 'Created by: Jill E. Thomley'
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document:
    code_folding: hide
---

*** 

## Replicate the content of the graphs shown on [this page](https://www.esrl.noaa.gov/gmd/ccgg/trend_mean_co2s/full.html).


```{r, message=FALSE}
library(knitr)
opts_chunk$set(comment = "", message = FALSE, warning = FALSE)

# Read in the datasets and load any necessary packages here
# Suppress the code and any messages / warnings it produces

library(dplyr)    # needed for cool data manipulation, like filter and mutate
library(tidyr)    # needed for data reshaping function /gather/
library(ggplot2)  # needed for cool data visualization
library(ggthemes) # needed for some plot themes

# ANNUAL  <- read.csv("CO2annualM.csv")
# co2_monthly <- read.csv("CO2co2_monthlyM.csv")
# WEEKLY  <- read.csv("CO2weeklyM.csv")
# GROWTH  <- read.csv("CO2growthM.csv")

# Read in datasets here
co2_monthly <-
  read.table(file = url("ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_mm_mlo.txt"),
             col.names = c("year", 
                           "month", #what are my variable names gonna be. #case when = if, else statement
                           "date", 
                           "mean_co2", 
                           "int_mean_co2", 
                           "trend_mean_co2", 
                           "numdays")) %>%
  mutate(decade = case_when(year %in% 1950:1959 ~ "1950s", #colon(:) is vector notation
                            year %in% 1960:1969 ~ "1960s",
                            year %in% 1970:1979 ~ "1970s", #if the year is in the vector 1950, 1951...1959, then the
                            year %in% 1980:1989 ~ "1980s", #value of the variable decade equals "1950s"
                            year %in% 1990:1999 ~ "1990s",
                            year %in% 2000:2009 ~ "2000s",
                            year %in% 2010:2019 ~ "2010s"))

co2_annual <-
  read.table(file = url("ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_annmean_mlo.txt"),
             col.names = c("year", 
                           "mean_co2", 
                           "uncertainty")) %>%
  mutate(decade = case_when(year %in% 1950:1959 ~ "1950s",
                            year %in% 1960:1969 ~ "1960s",
                            year %in% 1970:1979 ~ "1970s",
                            year %in% 1980:1989 ~ "1980s",
                            year %in% 1990:1999 ~ "1990s",
                            year %in% 2000:2009 ~ "2000s",
                            year %in% 2010:2019 ~ "2010s"))
```

```{r}
NOAATHEME <- theme_base(base_size = 15) +
             theme(axis.ticks.length = unit(-0.15, "cm"),
                   axis.text.x = element_text(margin = unit(c(0.4, 0.4, 0.4, 0.4), "cm")), 
                   axis.text.y = element_text(margin = unit(c(0.4, 0.4, 0.4, 0.4), "cm")),
                   plot.title = element_text(hjust = 0.5, margin = unit(c(0, 0, -0.4, 0), "cm")),
                   plot.background = element_blank())
```

```{r, echo=FALSE}
ggplot(co2_monthly) +
  geom_line(aes(x = date, y = int_mean_co2), color = "red") +
  geom_line(aes(x = date, y = trend_mean_co2), color = "black") +
  ggtitle(expression("Atmospheric CO"[2]*" at Mauna Loa Observatory")) +
  scale_x_continuous(breaks = seq(1960, 2020, 5), #where are the tick marks;  
                     labels = c("1960", "",                   #want seq from 1960-2020 in increments of 5
                                "1970", "",  #labels is how are the tick marks labeled
                                "1980", "",    #1980, blank
                                "1990", "", 
                                "2000", "",
                                "2010", "", 
                                "2020"),
                     limits = c(min(co2_monthly$year), 2020),
                     sec.axis = dup_axis(labels = NULL, name = "")) +  
  scale_y_continuous(breaks = seq(320, 410, 10), 
                     labels = c("320", "",
                                "340", "",
                                "360", "",
                                "380", "",
                                "400", ""),
                     sec.axis = dup_axis(labels = NULL, name = "")) +
  ylab("PARTS PER MILLION") +
  xlab("YEAR") +
  NOAATHEME
```

```{r, echo=FALSE}
co2_monthly2014 <- co2_monthly %>% filter(year >= 2015)

ggplot(co2_monthly2014) +
  geom_line(aes(x = date, y = int_mean_co2), col = "red", linetype = 5) +
  geom_point(aes(x = date, y = int_mean_co2), col = "red", shape = 18) +
  geom_line(aes(x = date, y = trend_mean_co2), col = "black") +
  geom_point(aes(x = date, y = trend_mean_co2), col = "black", shape = 15) +
  scale_x_continuous(breaks = seq(2015, 2020, .25), 
                     labels = c("2015", rep("", 3), 
                                "2016", rep("", 3),
                                "2017", rep("", 3),
                                "2018", rep("", 3),
                                "2019", rep("", 3),
                                "2020"),
                     limits = c(2015, 2020),
                     sec.axis = dup_axis(labels = NULL, name = "")) +
  scale_y_continuous(breaks = 395:415, 
                     labels = c("395", rep("", 4),
                                "400", rep("", 4),
                                "405", rep("", 4),
                                "410", rep("", 4),
                                "415"),
                     limits = c(395, 415),
                     sec.axis = dup_axis(labels = NULL, name = "")) +
  labs(title = expression("RECENT MONTHLY MEAN CO"[2]*" AT MAUNA LOA"),
       y = "PARTS PER MILLION",
       x = "YEAR") +
  NOAATHEME

# Note: expand = c(0, 0) will get rid of the exta padding at the ends
# of the x-axis, but the tick marks and axis lines will overlap oddly 
```


***
## Create variations on the last five years plot

```{r}
ggplot(filter(co2_monthly, year >= 2015)) +
  geom_line(aes(x = date, y = int_mean_co2), color = "gold") +
  geom_line(aes(x = date, y = trend_mean_co2), color = "yellow", linetype = "dashed") +
  labs(title = expression("Monthly Atmospheric CO"[2]*" at Mauna Loa Observatory"),
       subtitle = "last four complete years plus current year, raw (solid) and seasonally adjusted (dashed) values",
       x = "Year",
       y = expression("CO"[2]*" (ppm)"),
       caption = "Source: https://www.esrl.noaa.gov/gmd/ccgg/trends/index.html") +
  theme_dark()
```

```{r}
co2_monthly %>% 
  filter(year >= 2015) %>% 
  gather(type, co2, c(int_mean_co2, trend_mean_co2)) %>% 
  select(year, date, type, co2) %>% 
  mutate(type = ifelse(type == "int_mean_co2", "raw", "adjusted")) %>% 
  ggplot(aes(x = date, y = co2, color = type)) +
  geom_line() +
  geom_point(size = .6) +
  labs(title = expression("Monthly Atmospheric CO"[2]*" at Mauna Loa Observatory"),
       subtitle = "last four complete years plus current year, raw and seasonally adjusted values",
       x = "Year",
       y = expression("CO"[2]*" (ppm)"),
       caption = "Source: https://www.esrl.noaa.gov/gmd/ccgg/trends/index.html") +
  scale_color_manual(values = c("red", "purple")) +
  theme_linedraw()
```

```{r}
co2_monthly %>% 
  filter(year >= 2015) %>% 
  gather(type, co2, c(int_mean_co2, trend_mean_co2)) %>% 
  select(year, date, type, co2) %>% 
  mutate(type = ifelse(type == "int_mean_co2", "raw", "adjusted")) %>% 
  ggplot(aes(x = date, y = co2, color = type)) +
  geom_line() +
  geom_point(size = .6) +
  labs(title = expression("Monthly Atmospheric CO"[2]*" at Mauna Loa Observatory"),
       subtitle = "raw and seasonally adjusted values for the current and last four complete years",
       x = "",
       y = expression("CO"[2]*" (ppm)"),
       caption = "Source: https://www.esrl.noaa.gov/gmd/ccgg/trends/index.html") +
  scale_color_manual(values = c("black", "blue")) +
  theme_economist() +
  theme(legend.title = element_blank())
```

```{r}
# Adapted student example with theme modification
# Which theme element controls each plot feature?

co2_monthly %>% filter(year >= 2015) %>% 
  ggplot() + 
  geom_line(aes(x = date, y = trend_mean_co2), col = "black") +
  geom_point(aes(x = date, y = trend_mean_co2), col = "coral3", shape = 18) +
  geom_line(aes(x = date, y = int_mean_co2), col = "coral3", alpha = .90) + 
  geom_point(aes(x = date, y = int_mean_co2), col = "black", shape = 15) +
  labs(title = expression("Monthly CO"[2]*" at Mauna Loa"), 
       y = expression("CO"[2]*" (ppm)"),
       x = "Year") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'mistyrose1'),
        panel.grid.major = element_line(colour = "seashell1", size = 2),
        panel.grid.minor = element_line(colour = "rosybrown2", size = .25, linetype = "solid"),
        panel.border = element_blank(),
        axis.line.x = element_line(colour = "snow4", size = 1.5, lineend = "butt"),
        axis.line.y = element_line(colour = "snow4", size = 1.5))
```

```{r}
# Adapted student example with additional data
# Also shows how to get a legend without gather

newcdata <- co2_monthly %>%
  group_by(year) %>%
  mutate(meanc = mean(int_mean_co2)) %>%
  filter(year >= 2015)

ggplot(data = filter(co2_monthly, year >= 2015)) + 
  geom_point(aes(x = date, y = trend_mean_co2), size = .05) + 
  geom_line(aes(x = date, y = trend_mean_co2, color = "Trend Mean CO2")) +
  geom_point(aes(x = date, y = int_mean_co2), size = .01) +
  geom_line(aes(x = date, y = int_mean_co2, color = "Interpolated Mean CO2"), linetype = 2) + 
  geom_point(data = newcdata, aes(x = year, y = meanc, col = "Yearly Mean CO2")) +
  ggtitle(expression("RECENT MONTHLY MEAN CO"[2]*" AT MAUNA LOA")) +
  ylab("PARTS PER MILLION") +
  xlab("YEAR") +
  scale_color_manual(values = c("darkturquoise", "purple", "deeppink")) +
  theme_economist()
```

***
## Other graphs using the Mauna Loa CO~2~ data

```{r}
# inspiration: https://www.climatecentral.org/news/world-passes-400-ppm-threshold-permanently-20738

ggplot(filter(co2_monthly, year >= 2015)) +
  geom_line(aes(x = date, y = int_mean_co2), color = "gold") +
  geom_line(aes(x = date, y = trend_mean_co2), color = "yellow", linetype = "dashed") +
  geom_hline(yintercept = 400, color = "red", linetype = "dashed") +
  labs(title = expression("Atmospheric CO"[2]*" at Mauna Loa: Critical Threshold Reached"),
       subtitle = expression("trends in raw (solid) and seasonally adjusted (dashed) CO"[2]*" data since 2015"),
       x = "Year",
       y = expression("CO"[2]*" (ppm)"),
       caption = "Source: https://www.esrl.noaa.gov/gmd/ccgg/trends/index.html") +
  geom_point(filter(co2_monthly, year == 2016, month == 9), 
             mapping = aes(x = date, y = int_mean_co2), 
             color = "red", size = 2) +
  annotate("text", 
           x = 2016.85, 
           y = 401, 
           hjust = 0, 
           label = "September 2016", 
           color = "white") +
  annotate("text", 
           x = 2017.25, 
           y = 399.45, 
           label = "symbolic critical threshold for climate change", 
           color = "white") +
  annotate("text", 
           x = 2017.25, 
           y = 398.45, 
           label = "yearly minimum was below this level prior to 2016", 
           color = "white") +
  theme_dark()
```

```{r}
ggplot(filter(co2_monthly, !decade %in% c("1950s", "2010s")), 
       aes(x = date, y = int_mean_co2, color = decade)) +
  geom_point(size = 0.25) +
  geom_smooth(method = "lm") +
  labs(title = expression("Monthly Atmospheric CO"[2]*" at Mauna Loa Observatory"),
       subtitle = "with fitted linear models for each decade from 1960s through 2000s",
       x = "measurement date",
       y = expression("CO"[2]*" (ppm)"),
       caption = "Source: https://www.esrl.noaa.gov/gmd/ccgg/trends/index.html") +
  scale_color_brewer(palette = "Set1") +   # https://www.datanovia.com/en/blog/the-a-z-of-rcolorbrewer-palette/
  theme_linedraw()
```

```{r}
# Adapted from a student example

filter(co2_monthly, year >= 1960, year < 2019) %>% 
  ggplot() +
    geom_point(aes(date, int_mean_co2), size = 0.2) + 
    geom_smooth(aes(date, int_mean_co2, color = decade), method = "lm", se = FALSE, size = 1.3) + 
    scale_x_continuous(breaks = seq(1960, 2020, 10)) +
    scale_y_continuous(breaks = seq(300, 400, 10)) +
    labs(title = "Trends Over Time in CO2 Growth", 
         x = "YEAR", 
         y = "MEAN CO2") + 
    theme_excel()
```

```{r}
ggplot(co2_annual, aes(x = year, y = mean_co2)) +
  geom_bar(stat = "identity", width = 0.5, fill = "lightblue", color = "lightblue") +
  geom_smooth(color = "blue") +
  scale_x_continuous(breaks = seq(1960, 2020, 5)) +
  scale_y_continuous(breaks = seq(0, 400, 50)) +
  labs(title = expression("Annual Mean Atmospheric CO"[2]*" at Mauna Loa Observatory"),
       subtitle = "with loess smoothed trend curve and estimated historical reference values",
       x = "measurement year",
       y = expression("CO"[2]*" (ppm)"),
       caption = "data source: https://www/esrl.noaa.gov/gmd/ccgg/trends/data.html") +
  geom_hline(yintercept = c(200, 280, 400), 
             color = c("black", "black", "red")) +
  annotate("label", x = 1987.5, 
           y = c(200, 280, 400), 
           label = c("ice age mean", "pre-industrial mean", "crisis threshold")) +
  theme_classic()
```