---
title: 'NOAA Plot Replication and Variation'
author: 'Created by: Jill E. Thomley'
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document:
    code_folding: hide
---

*** 

## Replicate the content of the graphs shown on [this page](https://www.esrl.noaa.gov/gmd/ccgg/trend_mean_co2s/full.html).


```{r, message=FALSE}
library(knitr)
opts_chunk$set(comment = "", message = FALSE, warning = FALSE)

# Read in the datasets and load any necessary packages here
# Suppress the code and any messages / warnings it produces

library(dplyr)    # needed for cool data manipulation, like filter and mutate
library(tidyr)    # needed for data reshaping function /gather/
library(ggplot2)  # needed for cool data visualization
library(ggthemes) # needed for some plot themes

# ANNUAL  <- read.csv("CO2annualM.csv")
# co2_monthly <- read.csv("CO2co2_monthlyM.csv")
# WEEKLY  <- read.csv("CO2weeklyM.csv")
# GROWTH  <- read.csv("CO2growthM.csv")

# Read in datasets here
co2_monthly <-
  read.table(file = url("ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_mm_mlo.txt"),
             col.names = c("year", 
                           "month", #what are my variable names gonna be. #case when = if, else statement
                           "date", 
                           "mean_co2", 
                           "int_mean_co2", 
                           "trend_mean_co2", 
                           "numdays")) %>%
  mutate(decade = case_when(year %in% 1950:1959 ~ "1950s", #colon(:) is vector notation
                            year %in% 1960:1969 ~ "1960s",
                            year %in% 1970:1979 ~ "1970s", #if the year is in the vector 1950, 1951...1959, then the
                            year %in% 1980:1989 ~ "1980s", #value of the variable decade equals "1950s"
                            year %in% 1990:1999 ~ "1990s",
                            year %in% 2000:2009 ~ "2000s",
                            year %in% 2010:2019 ~ "2010s"))

co2_annual <-
  read.table(file = url("ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_annmean_mlo.txt"),
             col.names = c("year", 
                           "mean_co2", 
                           "uncertainty")) %>%
  mutate(decade = case_when(year %in% 1950:1959 ~ "1950s",
                            year %in% 1960:1969 ~ "1960s",
                            year %in% 1970:1979 ~ "1970s",
                            year %in% 1980:1989 ~ "1980s",
                            year %in% 1990:1999 ~ "1990s",
                            year %in% 2000:2009 ~ "2000s",
                            year %in% 2010:2019 ~ "2010s"))
```

```{r}
NOAATHEME <- theme_base(base_size = 15) +
  theme(axis.ticks.length = unit(-0.15, "cm"),
                   axis.text.x = element_text(margin = unit(c(0.4, 0.4, 0.4, 0.4), "cm")), 
                   axis.text.y = element_text(margin = unit(c(0.4, 0.4, 0.4, 0.4), "cm")),
                   plot.title = element_text(hjust = 0.5, margin = unit(c(0, 0, -0.4, 0), "cm")),
                   plot.background = element_blank())
```

```{r}
ggplot(co2_monthly) +
  geom_line(aes(x = date, y = int_mean_co2), color = "red") +
  geom_line(aes(x = date, y = trend_mean_co2), color = "black") +
  labs(title = expression("Atmospheric CO"[2]*" at Mauna Loa Observatory"),
       x = "YEAR",
       y = "PARTS PER MILLION") +
 scale_x_continuous(breaks = seq(1960, 2020, 5),
                    labels = c("1960", "",                   
                                "1970", "", 
                                "1980", "",
                                "1990", "", 
                                "2000", "",
                                "2010", "", 
                                "2020"),
                    limits = c(min(co2_monthly$year), 2020),
                    sec.axis = dup_axis()) +
NOAATHEME


```
